///<reference types = "Cypress"/>
describe("My EpsoapplicationoneTest Suite", function(){
    it("My EpsoapplicationoneTest case", function(){
        cy.visit("https://europa.eu/epso/application/passport/login.cfm?islo=true")
        cy.get('.ea_ignore').click()
        cy.get('.cck-actions > .wt-link').click()
        cy.get('input[name="login"]').type('janarthanan')
        cy.get('input[name="password"]').type('jana12345@$')
        cy.get('button[type="submit"]').click()
        cy.contains('Personal data').click()
        cy.contains('Upload CV').click()
        const filepath = 'Fileupload/sample.png'
        cy.get('input[name="file_contents"]').attachFile(filepath)
        cy.get('span.text').click()
        cy.log('File is uploaded')
        cy.contains('Upload supporting documents').click()
        cy.get('#fileType').select('Education')
        cy.get('#displayName').type('File Upload')
        const filepath1 = 'Fileupload/0558-how-to-make-a-computer-operating-system.pdf'
        cy.get('input[name="uploadFile"]').attachFile(filepath1)
        cy.get('button[type="submit"]').click()
        cy.contains('Your file was successfully saved.')
        cy.contains('Additional Information').click()
        cy.get('#field_selection').select('TRES SECRET UE / EU TOP SECRET')
        cy.get('select[name="security_clearance_validity_day"]').select('31')
        cy.get('select[name="security_clearance_validity_month"]').select('DECEMBER')
        cy.get('select[name="security_clearance_validity_year"]').select('2030')
        cy.contains('Save').click()
        cy.log('Your additional information was saved')
        cy.get('a[title="My Skills"]').click()
        cy.get('#skill-253').uncheck()
        cy.get('#skill-255').check()
        cy.get('#skill-385').uncheck()
        cy.get('#skill-382').check()
        cy.get('#skill-264').uncheck()
        cy.get('#skill-265').check()
        cy.get('input[value="267"]').uncheck()
        cy.get('#skill-266').check()
        cy.get('#skill-286').uncheck()
        cy.get('#skill-282').check()
        cy.get('input[value="365"]').uncheck()
        cy.get('#skill-367').check()
        cy.get('#skill-372').uncheck()
        cy.get('#skill-370').check()
        cy.get('input[value="374"]').uncheck()
        cy.get('#skill-377').check()
        cy.get('#skill-380').uncheck()
        cy.get('#skill-381').check()
        cy.contains('Save').click()
        cy.contains('MS Office ® skills').click()
        cy.get('#option-296-293').click()
        cy.get('#option-297-293').click()
        cy.get('#option-298-294').click()
        cy.get('#option-299-292').click()
        cy.get('#option-300-293').click()
        cy.get('#option-301-293').click()
        cy.contains('Save').click()
        cy.log('Your skills were saved')
        cy.contains('Personal Data Protection').click()
        cy.contains('Change my Password').click()
        // cy.get('#f_pass_old').type('jana12345@$')
        // cy.get('#f_pass_a').type('jana1234@$')
        // cy.get('input[name="f_pass_b"]').type('jana1234@$')
        // cy.contains('Confirm').click()
        cy.contains('Delete my EPSO Account').click()
    })
})