///<reference types = "Cypress"/>
describe("My EpsoapplicationTest Suite", function(){
    it("My EpsoapplicationTest case", function(){
        cy.visit("https://europa.eu/epso/application/passport/login.cfm?islo=true")
        cy.get('.ea_ignore').click()
        cy.get('.wt-link > svg').click()
        cy.get('input[name="login"]').type('janarthanan')
        cy.get('input[type="password"]').type('jana12345@$')
        cy.get('button[type="submit"]').click()
        cy.get("a[href='https://epso.europa.eu/en/job-opportunities/in-progress']").click()
        cy.get('.ea_ignore').click()
        cy.get('.wt-link > svg').click()
        cy.get('#superfish-main-toggle').click()
        cy.get('#block-footermenu > ul > :nth-child(3) > a').click()
        cy.contains('Secretaries/Clerks (CAST Permanent)').click()
        cy.contains('Apply for EPSO/CAST/P/6/2017 - FGII').invoke('removeAttr','target').click()
        cy.get('input[name="login"]').type('janarthanan')
        cy.get('input[name="password"]').type('jana12345@$')
        cy.get('button[type="submit"]').click()
        cy.get('select[name="legal_doc_type_id"]').select('Identity Card')
        cy.get('input[id="legal_doc_info"]').type('ABC12345', {force: true})
        cy.get('select[name="cbt_sitecode"]').select('Belgium - BRUSSELS')
        cy.get('select[id="lang_id_1"]').select('English')
        cy.get('select[id="lang_id_2"]').select('French')
        cy.get('select[id="media_idx"]').select('EU-Careers.eu / EPSO website')
        cy.get('button[id="save_next_button"]').click()
        cy.get('input[id="education_start_date_1"]').type('08/06/2015')
        cy.get('input[id="education_end_date_1"]').type('28/05/2019')
        cy.get('select[id="education_type_1"]').select('Science')
        cy.get('input[id="unlisted_category_1"]').type('Information science')
        cy.get('textarea[id="education_establishment_1"]').type('The Cross-Cultural Foundation of Uganda (CCFU), Makerere Hill Road, Block 9 - Plot 283, P. O. Box 25517, KAMPALA - Uganda')
        cy.get('textarea[name="education_subjects_1"]').type('Software Engineering, Programming, Data Structures and applications, Database Management, Cryptography, Network Security and Cyber Law')
        cy.get('select[id="diploma_country_id_1"]').select('France')
        cy.get('select[id="diploma_id_1"]').select('Diplôme de fin de deuxième cycle des études médicales (DF2CEM)')
        cy.get('input[id="education_title_1"]').type('Information for authors',{force: true})
        cy.get('textarea[id="education_level_1"]').type('Classification, Book Classification, Bibliographic Classification')
        cy.get('button[id="save_next_button"]').click()
        cy.get('input[id="add_entry_button"]').click()
        cy.get('input[id="experience_start_date_1"]').type('03/06/2019')
        cy.get('input[id="experience_end_date_1"]').type('02/08/2025')
        cy.get('input[id="experience_month_count_1"]').type('74')
        cy.get('input[id="experience_day_count_1"]').type('30')
        cy.get('select[id="wexp_type_id_1"]').select('Computers, Software')
        cy.get('input[id="unlisted_type_1"]').type('System software',{force: true})
        cy.get('select[id="wexp_class_id_1"]').select('Non-government Organisation (other areas)')
        cy.get('input[id="unlisted_class_1"]').type('Application software',{force: true})
        cy.get('textarea[name="experience_biztype_1"]').type('Database software')
        cy.get('textarea[name="experience_employer_1"]').type('Franklin Lee, CBI Industries, 39 Main Street Townville, New Hampshire 03060')
        cy.get('textarea[name="experience_occupation_1"]').type('Software design')
        cy.get('textarea[name="experience_duties_1"]').type('Improving system quality by identifying issues and common patterns, and developing standard operating procedures')
        cy.get('#add_entry_button').click()
        cy.get('#experience_start_date_2').type('03/06/2019')
        cy.get('#experience_end_date_2').type('02/08/2025')
        cy.get('#experience_month_count_2').type('74')
        cy.get('#experience_day_count_2').type('30')
        cy.get('#wexp_type_id_2').select('Computers, Software')
        cy.get('#unlisted_type_2').type('System software',{force: true})
        cy.get('#wexp_class_id_2').select('Non-government Organisation (other areas)')
        cy.get('#unlisted_class_2').type('Application software',{force: true})
        cy.get("textarea[name='experience_biztype_2']").type('Database software')
        cy.get("textarea[name='experience_employer_2']").type('Franklin Lee, CBI Industries, 39 Main Street Townville, New Hampshire 03060')
        cy.get("textarea[name='experience_occupation_2']").type('Software design')
        cy.get("textarea[name='experience_duties_2']").type('Improving system quality by identifying issues and common patterns, and developing standard operating procedures')
        cy.get('#save_next_button').click()
        cy.get('select[name="language_id_1"]').select('English')
        cy.get('select[name="listen_level_1"]').select('Independent user (B1)')
        cy.get('select[name="read_level_1"]').select('Independent user (B1)')
        cy.get('select[name="speak_level_1"]').select('Independent user (B1)')
        cy.get('select[name="write_level_1"]').select('Independent user (B1)')
        cy.get('select[name="language_id_2"]').select('French')
        cy.get('select[name="listen_level_2"]').select('Proficient user (C1)')
        cy.get('select[name="read_level_2"]').select('Proficient user (C1)')
        cy.get('select[name="speak_level_2"]').select('Proficient user (C1)')
        cy.get('select[name="write_level_2"]').select('Proficient user (C1)')
        cy.get('button[id="save_next_button"]').click()
        cy.get('textarea[id="motivation_1"]').type('Vous êtes capable de réaliser les missions demandées et vous pouvez obtenir des résultats. Vous tenez la combinaison parfaite entre compétences et expériences. Ce qu’il vous faut montrer au recruteur est : qu’est-ce qui vous démarque des autres candidats ? Quels sont vos qualités uniques ? Il est donc indispensable que vous prépariez votre réponse à l’avance en vous aidant des étapes suivantes.')
        cy.get('textarea[id="motivation_2"]').type('Sur un marché tendu où la concurrence est féroce, prononcer les mots qu’il faut au bon moment peut vous faire décrocher le poste auquel vous aspirez tant. Préparez-vous grâce à nos bonnes réponses aux questions délicates posées en entretien.')
        cy.get('textarea[id="motivation_3"]').type('Ce faisant, ils nous invitent à considérer la qualité de vie au travail non comme un ensemble de remèdes à des maux que pourraient générer nos organisations, mais comme une démarche globale visant à éviter que ces maux apparaissent et, au-delà, à créer les conditions pour que la personne puisse se développer dans toutes ses dimensions. Puisse se développer, et non être développée, car placer la personne en situation de faire ses choix elle-même est une condition fondamentale du respect de sa dignité.')
        cy.get('textarea[id="motivation_4"]').type('Avec cette question, l’employeur vérifie dans quoi vous excellez pour mesurer comment vos forces pourront lui être utiles», indique Annie Chauvette, conseillère en main-d’œuvre pour le Centre d’intervention des Basses-Laurentides pour l’emploi.')
        cy.get('button[id="save_next_button"]').click()
        cy.get('input[value="yes"]').check()
        cy.get('#save_edit_confirm_button').click()
        cy.get('#move_to_next_tab_button').click()     
        cy.contains('Validate Application').each(($btn)=>{
            if($btn.is(':enabled')){
               cy.contains('Validate Application').click()
            }
            else
            {
                cy.log("Element is not clickable")
            }
        })
        // cy.contains('Validate Application').click()
        cy.get(':nth-child(1) > :nth-child(2) > #validate_div > .popupBox-inner > .dataTable > tbody > :nth-child(2) > :nth-child(2)').type('jana12345@$')
        cy.get(':nth-child(1) > :nth-child(2) > #validate_div > .popupBox-inner > .dataTable > tbody > :nth-child(3) > :nth-child(2) > [value="Cancel"]').click()
        cy.get('#info_message_span').then(function(element){
            const actualText = element.text()
            expect(actualText.includes("Your application is correct and can be validated.")).to.be.true
        })
        
    })
})